name: Call Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: CristianMontanoP/Reusable-Repository/.github/workflows/reusable-workflow.yml@main
    # with:
    #   ENV_VARIABLE: ${{ vars.ENV_VARIABLE }}
    # secrets:
    #   ENV_SECRET: ${{ secrets.ENV_SECRET }}
    secrets: inherit