name: Caller workflow
on:
  workflow_dispatch:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Call reusable workflow
        uses: CristianMontanoP/Reusable-Repository/.github/workflows/reusable-workflow.yml@main 
        with:
          ENV_VARIABLE: ${{ vars.ENV_VARIABLE }}
        secrets:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
    